/**
 * Agent detection heuristics for identifying AI-assisted coding activity.
 * Detects Claude Code, Devin, Cursor, Windsurf, and other agents.
 */

import type { ActivitySource, ActorType } from "@/types/activity";

/** Known agent commit message signatures */
const AGENT_COMMIT_PATTERNS: { pattern: RegExp; agent: ActivitySource }[] = [
  // Claude Code patterns
  { pattern: /\bco-authored-by:.*claude\b/i, agent: "claude_code" },
  { pattern: /\bgenerated by claude\b/i, agent: "claude_code" },
  { pattern: /\[claude\]/i, agent: "claude_code" },
  { pattern: /\bco-authored-by:.*anthropic\b/i, agent: "claude_code" },

  // Devin patterns
  { pattern: /\bco-authored-by:.*devin\b/i, agent: "devin" },
  { pattern: /\bdevin-ai\b/i, agent: "devin" },
  { pattern: /\[devin\]/i, agent: "devin" },

  // Cursor patterns
  { pattern: /\bcursor\b.*\bgenerated\b/i, agent: "cursor" },
  { pattern: /\[cursor\]/i, agent: "cursor" },

  // Windsurf/Cascade patterns
  { pattern: /\bwindsurf\b/i, agent: "windsurf" },
  { pattern: /\[cascade\]/i, agent: "windsurf" },
  { pattern: /\[windsurf\]/i, agent: "windsurf" },

  // GitHub Copilot
  { pattern: /\bcopilot\b/i, agent: "copilot" },
];

/** Known agent command patterns */
const AGENT_COMMAND_PATTERNS: { pattern: RegExp; agent: ActivitySource }[] = [
  { pattern: /\bclaude\b/i, agent: "claude_code" },
  { pattern: /\banthropic\b.*\bcli\b/i, agent: "claude_code" },
  { pattern: /\bdevin\b/i, agent: "devin" },
  { pattern: /\bcursor\b/i, agent: "cursor" },
  { pattern: /\bwindsurf\b/i, agent: "windsurf" },
];

/** Known agent environment variable indicators */
const AGENT_ENV_INDICATORS: { key: string; agent: ActivitySource }[] = [
  { key: "CLAUDE_CODE", agent: "claude_code" },
  { key: "CURSOR_SESSION", agent: "cursor" },
  { key: "CURSOR_TRACE_ID", agent: "cursor" },
  { key: "WINDSURF_SESSION", agent: "windsurf" },
  { key: "DEVIN_SESSION", agent: "devin" },
  { key: "DEVIN_ENV", agent: "devin" },
];

/** Detect agent from a commit message */
export function detectAgentFromCommit(
  message: string
): { agent: ActivitySource; actor: ActorType } | null {
  for (const { pattern, agent } of AGENT_COMMIT_PATTERNS) {
    if (pattern.test(message)) {
      return { agent, actor: "agent" };
    }
  }
  return null;
}

/** Detect agent from a CLI command */
export function detectAgentFromCommand(
  command: string
): ActivitySource | null {
  for (const { pattern, agent } of AGENT_COMMAND_PATTERNS) {
    if (pattern.test(command)) {
      return agent;
    }
  }
  return null;
}

/** Detect agent from environment variables */
export function detectAgentFromEnv(
  env: Record<string, string | undefined>
): ActivitySource | null {
  for (const { key, agent } of AGENT_ENV_INDICATORS) {
    if (env[key]) {
      return agent;
    }
  }
  return null;
}

/** Get a human-readable label for an agent source */
export function getAgentLabel(source: ActivitySource): string {
  const labels: Record<ActivitySource, string> = {
    github: "GitHub",
    cursor: "Cursor",
    windsurf: "Windsurf",
    devin: "Devin",
    claude_code: "Claude Code",
    copilot: "GitHub Copilot",
    cli: "CLI",
  };
  return labels[source];
}

/** Get actor type description */
export function getActorLabel(actor: ActorType): string {
  const labels: Record<ActorType, string> = {
    human: "Human",
    agent: "Agent",
    mixed: "Mixed",
  };
  return labels[actor];
}
